skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
probatio = "HRGEAiqX4qw7B1fgNsR64oRAKF4QwkjkZFx9YXDFxaXA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
